spring:
  datasource:
    url: jdbc:mysql://comma-mysql-account:7001/comma_account?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
  flyway:
    url: jdbc:mysql://comma-mysql-account:7001/comma_account?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC

