jwt:
  secretKey: efwalfjiiljgkneiegojioa8e
  access:
    expiration: 3600000
    header: Authorization
  refresh:
    expiration: 1209600000
    header: Authorization-refresh

spring:
  datasource:
    url: jdbc:mysql://comma-mysql-account:7001/comma_account?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC

